### Create new cooking log
POST http://localhost:3001/api/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NzcyZjBjMjEzY2NkY2Y2M2I5ZmYwYjMiLCJpYXQiOjE3MzU1OTQxMDEsImV4cCI6MTczNTU5NzcwMX0.Z0scz5Xcy0rfafkfvTL2iJC72JBgb5wl_wlCeezobTk
Content-Type: application/json

{
  "fishId": "6771b1f1ec0aa062e84409af",
  "name": "Pan-fried Snapper",
  "note": "step one step two step three",
  "rating": 5,
  "ingredients": ["butter", "lemon", "salt", "pepper"]
}

### Get your cooking logs
GET http://localhost:3001/api/logs/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NzcyZjBjMjEzY2NkY2Y2M2I5ZmYwYjMiLCJpYXQiOjE3MzU1OTQxMDEsImV4cCI6MTczNTU5NzcwMX0.Z0scz5Xcy0rfafkfvTL2iJC72JBgb5wl_wlCeezobTk

### Get a log (public)
GET http://localhost:3001/api/logs/6773187e357b6c8994cc20d8


### Update log
PUT http://localhost:3001/api/logs/6773187e357b6c8994cc20d8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NzcyZjBjMjEzY2NkY2Y2M2I5ZmYwYjMiLCJpYXQiOjE3MzU2MzM5NjMsImV4cCI6MTczNTYzNzU2M30.q_zzkI0PNc6TEspeAucupituql8GOEHyaJJ_16TT-hk

{
  "note": "Updated note",
  "rating": 4
}

### Delete log
DELETE http://localhost:3001/api/logs/677312c99220b0ceccc19d26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NzcyZjBjMjEzY2NkY2Y2M2I5ZmYwYjMiLCJpYXQiOjE3MzU1OTQxMDEsImV4cCI6MTczNTU5NzcwMX0.Z0scz5Xcy0rfafkfvTL2iJC72JBgb5wl_wlCeezobTk